# DenseNet121 Configuration for BUSI Dataset

# Model configuration
model:
  model_name: densenet
  version: '121'
  num_classes: 2
  pretrained: true

# Data configuration
data:
  data_dir: data/busi_dataset_raw/Dataset_BUSI_with_GT
  img_size: 224
  batch_size: 16
  num_workers: 4

# Training configuration
training:
  epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
  scheduler_step_size: 7
  scheduler_gamma: 0.1

# Paths
paths:
  checkpoints_dir: models/checkpoints
  results_dir: results 